default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rqtrap_dev
  username: rqtrap

test:
  <<: *default
  database: rqtrap_test
  username: rqtrap

production:
  <<: *default
  database: rqtrap_prod
  username: rqtrap
  password: <%= ENV['RQTRAP_DATABASE_PASSWORD'] %>
